### ISSUE TITLE
Integrate TDD Workflow

### ISSUE THREAD

**Issue by matthijsgroen** [alexgb/guard-konacha#16]
At Guard RSpec, there is a workflow hidden in the guard strategies:
1. safe a file or spec. The according testfile is ran
   2a. When this test passes, no special stuff
   2b. When this test fails, every file trigger should rerun this last failing spec (if no spec file matches)

This results in that when you have a failing spec file, saving a stylesheet or template will rerun this file (so the guard plugin assumes that you save these files to get the spec green)

When this spec file passes, all tests in the suite are ran (which could point you to the next failing spec that needs implementation)

I would like to see this behaviour as well for this plugin, but before I start development for it I want to ask if more people are interested in this behaviour.

**Comment by alexgb** [comment]
Sounds interesting, where do you see this in Guard RSpec?

**Comment by matthijsgroen** [comment]
I searched but could not find it as well :-/

Weird but their behavior seems like a really nice TDD flow

At this moment when you would save a template or css file no konacha is run. But what if you would save a template or css file to make your last failing test pass? With the above description we could make that happen.

I also remember when the file passes (when failed earlier) all specs would run, but I can't find any of it in their code.

**Comment by matthijsgroen** [comment]
``` ruby
describe 'TDD behaviour' do

  context 'when single test file is run' do
     context 'when test file previously failed' do
       it 'reruns the previous file if a file is triggered without a spec'
       it 'runs all the tests if the test does now pass'
     end
     context 'when test file previously passed' do
       it 'does not run any tests if a file is triggered without a spec'
     end
  end

```

I think this is the behaviour I would like to implement

**Comment by alexgb** [comment]
+1. It would be good if we documented this behavior I think, even if guard-rspec does not.

**Comment by matthijsgroen** [comment]
Would a cucumber scenario be more appropriate then?

**Comment by matthijsgroen** [comment]
Started feature using cucumber, first work in progress (defining the scenario's) can be found here: https://github.com/matthijsgroen/guard-konacha/compare/feature-tdd-behaviour

**Comment by alexgb** [comment]
I only meant document the behavior in the Readme, but I trust your instinct wrt introducing Cucumber. This looks good to me.

**Comment by matthijsgroen** [comment]
I noticed i actually don't need this feature anymore. So I stopped the development of it. I will close this.
