### ISSUE TITLE
The :all_on_start => false is not respected

### ISSUE THREAD

**Issue by matthijsgroen** [alexgb/guard-konacha#19]
It will run all konacha tests regardless of the setting

**Comment by alexgb** [comment]
The option should be `:run_all_on_start => false`. Hopefully that's your issue. If not, can you see if you can make the spec I just added for this behavior to fail?

**Comment by matthijsgroen** [comment]
has this been changed between the versions? I was using the Guardfile of the previous release and left the option intact

**Comment by alexgb** [comment]
Yes, many of the configuration options changed. We now load the Konacha configuration file from the Rails project so most configuration is done there. See the new [Guardfile template](https://github.com/alexgb/guard-konacha/blob/master/lib/guard/konacha/templates/Guardfile)

**Comment by matthijsgroen** [comment]
The `:run_all_on_start` works as expected. I'll close this issue
