### ISSUE TITLE
Weird logging

### ISSUE THREAD

**Issue by re5et** [alexgb/guard-konacha#4]
I am seeing the following output.  There is no coloration and weird prefixing.  I was wondering if there was something I could do to change this to be more like the rspec output I am used to.

```
13:55:32 - INFO - Konacha Results: F
> [#] 
> [#]   Failed: tsum.test returns 0
> [#]     AssertionError: expected [Function] to equal 0
> [#] 
> [#] Finished in 0.00 seconds
> [#] 1 examples, 1 failed, 0 pending
nil
2;[Konacha Specs] 1 examples, 1 failed, 0 pending
```

**Comment by alexgb** [comment]
Thanks for reporting. I'll take a look at this when I can.

**Comment by alexgb** [comment]
Should be fixed now.
